apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secret
  namespace: sample-app
type: Opaque
stringData:
  APP_KEY: "base64:QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE="
  DB_USERNAME: "app_user"
  DB_PASSWORD: "app_password"
  MYSQL_ROOT_PASSWORD: "app_root_password"
